/**
 * ORB feature registration against a committed blank-form template.
 *
 * This module is pure on purpose: it takes an OpenCV module and Mats as
 * arguments and never touches a browser API, so the perspective worker and a
 * Node measurement harness call the *same* code (the same property that lets
 * detectDocumentQuad.ts be scored centrally). Keep it that way -- no
 * importScripts, no OffscreenCanvas, no DOM, no Node builtins.
 *
 * Template features are generated by scripts/generate-orb-template.cjs from
 * src/lib/recognition/assets/{cagi,satisfaction}-blank.png and committed as
 * orbTemplate.{cagi,satisfaction}.json next to this file.
 */

export interface OrbTemplate {
  /** Template frame width in px (1422 = cagi baseSize.width x 3). */
  width: number;
  /** Template frame height in px (1968 = cagi baseSize.height x 3). */
  height: number;
  /** Keypoint coordinates in the template frame, row i pairs with descriptor row i. */
  points: [number, number][];
  /** Base64 of the raw Uint8 ORB descriptor matrix, rows x 32 bytes. */
  descriptors: string;
}

export interface OrbAlignment {
  /**
   * 9 numbers, row-major. Maps photo (detection frame) -> template frame.
   * Null when there were too few good matches or RANSAC failed.
   */
  homography: number[] | null;
  inliers: number;
  goodMatches: number;
  /** inliers / goodMatches; 0 when no homography. */
  inlierRatio: number;
  /** [photoX, photoY, templateX, templateY] for each RANSAC inlier match. */
  inlierPairs: [number, number, number, number][];
}

/** Same feature budget the spike measured with (ADOPTION §3: 38/38 coverage). */
const ORB_FEATURE_COUNT = 3000;
/** Lowe ratio test threshold (ADOPTION §3: measured pipeline uses 0.75). */
const LOWE_RATIO = 0.75;
/** RANSAC reprojection threshold in px (ADOPTION §3: findHomography(RANSAC, 4.0)). */
const RANSAC_REPROJECTION_THRESHOLD_PX = 4.0;
/** Below this many Lowe-filtered matches a homography is not even attempted. */
const MIN_GOOD_MATCHES = 12;

/*
 * Decision constants. Provenance: Task/EXTERNAL_ADOPTION_PLAN_2026-08-27.md §3
 * (all provisional -- T3/T5 measurement refines them; per CLAUDE.md §5.4 they
 * may only be tightened, never relaxed, to produce gains).
 */

/**
 * "성공 사례 최소 60(sat-p14), 나쁜 워프 36(p10) 사이" -- the weakest
 * registration that scored sat inliers 60+, the known-bad warp p10 had 36.
 * ADOPTION §3.2~3.3.
 */
export const ORB_MIN_INLIERS = 50;

/**
 * "성공 최저 0.62(sat-p6), 나쁜 워프 0.49 사이" -- lowest good inlier ratio
 * observed 0.62, the bad warp p10 sat at 0.49. ADOPTION §3.2~3.3.
 */
export const ORB_MIN_RATIO = 0.55;

/**
 * Median residual (px, template frame 1422x1968) of ORB inlier pairs pushed
 * through the quad homography. "정상 잔차 5~10px대, p14는 130px대 환산" --
 * normal registrations sit at 5-10px, the p14 failure (one corner off by
 * 192px at full res) lands >100px, so 20 splits them with a 10x gap on both
 * sides. ADOPTION §3.1 (corner residuals on 711x984: 1.7-8.6 normal vs
 * 96.4 / 241.2 for the two known-bad warps).
 */
export const QUAD_RESIDUAL_MAX_PX = 20;

const BASE64_ALPHABET = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';

/**
 * Environment-free base64 decoder: workers have atob and Node has Buffer, but
 * this module must not care which host it is running in.
 */
export function decodeBase64ToBytes(base64: string): Uint8Array {
  const cleaned = base64.replace(/[\s=]+$/g, '');
  const lookup = new Int16Array(128).fill(-1);
  for (let i = 0; i < BASE64_ALPHABET.length; i++) {
    lookup[BASE64_ALPHABET.charCodeAt(i)] = i;
  }

  const outputLength = Math.floor((cleaned.length * 6) / 8);
  const bytes = new Uint8Array(outputLength);
  let buffer = 0;
  let bitsInBuffer = 0;
  let writeIndex = 0;

  for (let i = 0; i < cleaned.length; i++) {
    const code = cleaned.charCodeAt(i);
    const value = code < 128 ? lookup[code] : -1;
    if (value < 0) {
      throw new Error(`Invalid base64 character at index ${i}.`);
    }

    buffer = (buffer << 6) | value;
    bitsInBuffer += 6;
    if (bitsInBuffer >= 8) {
      bitsInBuffer -= 8;
      bytes[writeIndex] = (buffer >> bitsInBuffer) & 0xff;
      writeIndex += 1;
    }
  }

  return bytes;
}

/** Rebuilds the template descriptor Mat (rows x 32, CV_8U) from its base64 form. */
function descriptorMatFromBase64(cv: any, base64: string): any {
  const bytes = decodeBase64ToBytes(base64);
  if (bytes.length === 0 || bytes.length % 32 !== 0) {
    throw new Error(`Descriptor payload is ${bytes.length} bytes, not a multiple of 32.`);
  }

  const rows = bytes.length / 32;
  const mat = new cv.Mat(rows, 32, cv.CV_8U);
  mat.data.set(bytes);
  return mat;
}

/** Applies a row-major 3x3 homography to a point. */
export function applyHomography(homography: number[], x: number, y: number): [number, number] {
  const w = homography[6] * x + homography[7] * y + homography[8];
  const safeW = w === 0 ? Number.EPSILON : w;
  return [
    (homography[0] * x + homography[1] * y + homography[2]) / safeW,
    (homography[3] * x + homography[4] * y + homography[5]) / safeW,
  ];
}

/** Row-major 3x3 product a ∘ b: (a ∘ b)(x) = a(b(x)). */
export function multiplyHomographies(a: number[], b: number[]): number[] {
  const result = new Array<number>(9).fill(0);
  for (let row = 0; row < 3; row++) {
    for (let col = 0; col < 3; col++) {
      result[row * 3 + col] = a[row * 3] * b[col] +
        a[row * 3 + 1] * b[3 + col] +
        a[row * 3 + 2] * b[6 + col];
    }
  }
  return result;
}

/**
 * Rescales a homography estimated on a downscaled copy so it accepts
 * full-resolution coordinates.
 *
 * `homography` maps downscaled-photo coords -> template, and the downscaled
 * copy relates to the original as `downscaled = full * scale` (so
 * scaleX = detectionWidth / fullWidth <= 1). The full-res homography must
 * first take a full-res point into the detection frame and then apply H:
 *
 *   H_full = H ∘ diag(scaleX, scaleY, 1)
 *
 * (equivalently H ∘ diag(1/ux, 1/uy, 1) with u the upscale factor
 * fullWidth / detectionWidth -- the form the spec writes it in). Verified
 * numerically in tests/orb-align.test.ts.
 */
export function composeToFullRes(homography: number[], scaleX: number, scaleY: number): number[] {
  return multiplyHomographies(homography, [scaleX, 0, 0, 0, scaleY, 0, 0, 0, 1]);
}

/**
 * Median Euclidean distance |H(photoPt) - templatePt| in px over the pairs.
 *
 * Used to verify a DIFFERENT homography (the quad warp's, scaled into the
 * template frame) against ORB's matched pairs: a quad that traced the page
 * correctly moves the pairs onto their template positions, a quad that
 * "succeeded" with a displaced corner does not (ADOPTION §3.1, p14).
 * Returns +Infinity for an empty pair list so a caller that forgets to guard
 * fails verification instead of passing it.
 */
export function measureResidualPx(
  homography: number[],
  pairs: [number, number, number, number][],
): number {
  if (pairs.length === 0) {
    return Number.POSITIVE_INFINITY;
  }

  const errors = pairs.map(([photoX, photoY, templateX, templateY]) => {
    const [mappedX, mappedY] = applyHomography(homography, photoX, photoY);
    return Math.hypot(mappedX - templateX, mappedY - templateY);
  });
  errors.sort((a, b) => a - b);

  const middle = Math.floor(errors.length / 2);
  return errors.length % 2 === 1
    ? errors[middle]
    : (errors[middle - 1] + errors[middle]) / 2;
}

/**
 * ORB(3000) on the photo, BFMatcher NORM_HAMMING knnMatch k=2, Lowe 0.75,
 * findHomography(RANSAC, 4.0) against the committed template features.
 *
 * `photoGray` must be an 8UC1 Mat in the detection frame; the caller owns it.
 * Every Mat created here is deleted here.
 */
export function alignToTemplate(cv: any, photoGray: any, template: OrbTemplate): OrbAlignment {
  const noAlignment = (goodMatches: number): OrbAlignment => ({
    homography: null,
    inliers: 0,
    goodMatches,
    inlierRatio: 0,
    inlierPairs: [],
  });

  const orb = new cv.ORB(ORB_FEATURE_COUNT);
  const keypoints = new cv.KeyPointVector();
  const photoDescriptors = new cv.Mat();
  const emptyMask = new cv.Mat();
  const matcher = new cv.BFMatcher(cv.NORM_HAMMING, false);
  const knnMatches = new cv.DMatchVectorVector();
  let templateDescriptors: any = null;
  let sourcePoints: any = null;
  let destinationPoints: any = null;
  let inlierMask: any = null;
  let homographyMat: any = null;

  try {
    templateDescriptors = descriptorMatFromBase64(cv, template.descriptors);
    if (templateDescriptors.rows !== template.points.length) {
      throw new Error(
        `Template descriptor rows (${templateDescriptors.rows}) do not match point count (${template.points.length}).`,
      );
    }

    orb.detectAndCompute(photoGray, emptyMask, keypoints, photoDescriptors);
    if (photoDescriptors.rows === 0) {
      return noAlignment(0);
    }

    matcher.knnMatch(photoDescriptors, templateDescriptors, knnMatches, 2);

    const good: { photo: [number, number]; template: [number, number] }[] = [];
    for (let i = 0; i < knnMatches.size(); i++) {
      const pair = knnMatches.get(i);
      try {
        if (pair.size() < 2) {
          continue;
        }

        const first = pair.get(0);
        const second = pair.get(1);
        if (first.distance < LOWE_RATIO * second.distance) {
          const keypoint = keypoints.get(first.queryIdx);
          const templatePoint = template.points[first.trainIdx];
          good.push({
            photo: [keypoint.pt.x, keypoint.pt.y],
            template: [templatePoint[0], templatePoint[1]],
          });
        }
      } finally {
        // The inner DMatchVector is a fresh embind wrapper per get(); leaking
        // them is the jscanify long-session WASM failure mode.
        if (typeof pair.delete === 'function') {
          pair.delete();
        }
      }
    }

    if (good.length < MIN_GOOD_MATCHES) {
      return noAlignment(good.length);
    }

    const sourceFlat: number[] = [];
    const destinationFlat: number[] = [];
    for (const match of good) {
      sourceFlat.push(match.photo[0], match.photo[1]);
      destinationFlat.push(match.template[0], match.template[1]);
    }

    sourcePoints = cv.matFromArray(good.length, 1, cv.CV_32FC2, sourceFlat);
    destinationPoints = cv.matFromArray(good.length, 1, cv.CV_32FC2, destinationFlat);
    inlierMask = new cv.Mat();
    homographyMat = cv.findHomography(
      sourcePoints,
      destinationPoints,
      cv.RANSAC,
      RANSAC_REPROJECTION_THRESHOLD_PX,
      inlierMask,
    );

    if (!homographyMat || homographyMat.rows !== 3 || homographyMat.cols !== 3) {
      return noAlignment(good.length);
    }

    const homography = Array.from(homographyMat.data64F.slice(0, 9)) as number[];
    const inlierPairs: [number, number, number, number][] = [];
    for (let i = 0; i < good.length; i++) {
      if (inlierMask.data[i] === 1) {
        inlierPairs.push([
          good[i].photo[0],
          good[i].photo[1],
          good[i].template[0],
          good[i].template[1],
        ]);
      }
    }

    return {
      homography,
      inliers: inlierPairs.length,
      goodMatches: good.length,
      inlierRatio: inlierPairs.length / good.length,
      inlierPairs,
    };
  } finally {
    if (homographyMat && typeof homographyMat.delete === 'function') homographyMat.delete();
    if (inlierMask) inlierMask.delete();
    if (destinationPoints) destinationPoints.delete();
    if (sourcePoints) sourcePoints.delete();
    if (templateDescriptors) templateDescriptors.delete();
    knnMatches.delete();
    matcher.delete();
    emptyMask.delete();
    photoDescriptors.delete();
    keypoints.delete();
    orb.delete();
  }
}

/** What the dual-route decision settled on; the worker copies this into RegistrationMeta. */
export interface RegistrationDecision {
  method: 'quad' | 'orb' | 'none';
  /** Did the adopted homography pass its verification threshold? */
  verified: boolean;
  /** Median quad-H residual over ORB inlier pairs (template-frame px), null when unmeasurable. */
  quadResidualPx: number | null;
}

/**
 * The F1.2 decision table, kept pure so a Node harness can score the exact
 * rule the worker ships (FEATURE_SPEC_CAPTURE_PIPELINE_2026-08-27.md §F1.2):
 *
 * - quad accepted, residual <= max          -> quad, verified
 * - quad accepted, residual > max, ORB ok   -> orb, verified (the p14/p10 catch)
 * - quad accepted, residual > max, ORB weak -> quad, NOT verified (suspect)
 * - quad accepted, residual unmeasurable    -> quad, NOT verified
 * - quad rejected, ORB ok                   -> orb, verified
 * - neither                                 -> none
 */
export function decideRegistration(input: {
  quadAccepted: boolean;
  /** Quad homography mapped into the TEMPLATE frame; null when quad rejected. */
  quadHomographyToTemplate: number[] | null;
  alignment: OrbAlignment | null;
}): RegistrationDecision {
  const { quadAccepted, quadHomographyToTemplate, alignment } = input;
  const orbValid = Boolean(
    alignment &&
    alignment.homography &&
    alignment.inliers >= ORB_MIN_INLIERS &&
    alignment.inlierRatio >= ORB_MIN_RATIO,
  );

  const quadResidualPx = quadAccepted && quadHomographyToTemplate && alignment && alignment.inlierPairs.length > 0
    ? measureResidualPx(quadHomographyToTemplate, alignment.inlierPairs)
    : null;

  if (quadAccepted) {
    if (quadResidualPx !== null && quadResidualPx > QUAD_RESIDUAL_MAX_PX) {
      if (orbValid) {
        return { method: 'orb', verified: true, quadResidualPx };
      }
      return { method: 'quad', verified: false, quadResidualPx };
    }

    return { method: 'quad', verified: quadResidualPx !== null, quadResidualPx };
  }

  if (orbValid) {
    return { method: 'orb', verified: true, quadResidualPx };
  }

  return { method: 'none', verified: false, quadResidualPx };
}
